### ISSUE TITLE
Stuck in Optimal candidate selection for a long time, no error happen

### ISSUE THREAD

**Issue by HUAFOR** [aim-uofa/OIR#2]
Thank you for your great work!! When replicating your code for inference, I was stuck in this step for a long time(half an hour at least), with no error happen, using weights from sd1.5.

![image](https://github.com/user-attachments/assets/eb10a04c-f538-461f-9925-a3ae9a0726c4)

**Comment by HUAFOR** [comment]
update:
![image](https://github.com/user-attachments/assets/1738e391-e63f-4093-9cae-a605d1b56e64)

**Comment by ZhenYangCS** [comment]
Thank you for your question. I think the simplest solution is to try SD1.4 and compare whether it is a problem with the SD version. At the same time, you need to check the package version in requirements.txt. In addition, I would like to ask what version of GPU you are using?
